### ISSUE TITLE
errors with both DEV and PROD

### ISSUE THREAD

**Issue by yankeeinlondon** [samirdjelal/mail-dev#1]
I ran the set commands for both dev and prod but in both cases get the following sort of error:

```sh
tauri dev                                                                                                           ken@Whopper
[tauri]: running dev
 ERROR: tauri.conf.json has unknown property package +0ms
 ERROR: tauri.conf.json > tauri has unknown property updater +0ms
 ERROR: tauri.conf.json > tauri has unknown property windows +1ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property macOS +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property windows +0ms
```

Now I did notice that you're assuming a global install of `tauri` which goes against their recommendations though I agree it is more convenient but it would help to have this in the instructions. I did install it globally only to get this error. Now I'm not sure what I'm doing wrong.

**Comment by samirdjelal** [comment]
tauri-cli has been installed in the app, thanks 🙏
